INSERT INTO suppliers (name, product_id) VALUES
('ООО "Электроникс"', 1), ('ИП Петров', 1),
('Apple Rus', 2),
('Sony Store', 3),
('LG Official', 4),
('Apple Premium', 5),
('Apple Watch Distribution', 6),
('Dyson GmbH', 7),
('Roborock LLC', 8),
('Samsung Home', 9),
('LG Appliances', 10),
('Bosch Home', 11),
('Levi"s Russia', 12), ('ИП Смирнов', 12),
('Nike Store', 13),
('Adidas Russia', 14),
('North Face', 15),
('Zara Fashion', 16),
('Gucci Official', 17),
('Книжный мир', 18),
('АСТ', 19),
('Эксмо', 20),
 ('ФруктТорг', 21), ('Банановая республика', 22),
('Молокозавод №1', 23), ('Молокозавод №1', 24), ('Молокозавод №1', 25),
('Хлебзавод', 26),
('Сыроварня', 27),
('Мясокомбинат', 28),

 ('Dell Official', 29),
('Logitech Store', 30),
('Razer Store', 31),
('Logitech Store', 32),
('TP-Link', 33),
('Samsung Store', 34),
('Anker Russia', 35),

 ('DeLonghi', 36),
('Tefal', 37),
('Philips', 38),
('Redmond', 39),
('Tefal', 40),
 ('Puma Store', 41),
('Adidas Store', 42),
('Uniqlo Russia', 43),
('Tommy Hilfiger', 44),
 ('Издательство АСТ', 45), ('Издательство АСТ', 46), ('Издательство АСТ', 47),
('Эксмо', 48), ('Эксмо', 49),
 ('Молочная лавка', 50), ('Молочная лавка', 51), ('Молочная лавка', 52),
('КФХ "Веселая ферма"', 53),
('Пекарня №1', 54),
('Кондитер', 55),
 ('JBL', 56), ('JBL', 57),
('Garmin', 58),
('Xiaomi Global', 59),
('SanDisk', 60),
('Kingston', 61),
('Sony PlayStation', 62), ('Sony PlayStation', 63),
('Belkin', 64),
('Xiaomi Global', 65), ('Xiaomi Global', 66),
 ('Philips', 67), ('Bosch', 68), ('KitchenAid', 69),
('Сушилка ЛТД', 70),
('Indesit', 71),

 ('Норковая фабрика', 72),
('Columbia', 73),
('Zara', 74),
('Armani', 75),
('Hugo Boss', 76),
 ('Бомбора', 77), ('АСТ', 78), ('Просвещение', 79),
('Олимп', 80), ('АСТ', 81),

 ('Тархун', 82), ('Вода Байкал', 83), ('Соковая ферма', 84),
('Lipton', 85), ('Nescafe', 86), ('Granola', 87),
 ('Mechanic', 88),
('Logitech G', 89),
('Honor', 90),
('Manfrotto', 91),
('Xiaomi Mi Home', 92),
('Dell', 93),
('CableMaster', 94),
('UGreen', 95),
('Motorola', 96),

 ('Ballu', 97), ('Ballu', 98),
('DXRacer', 99),
 ('Универсальный поставщик', 100);
